language: cpp
branches:
  only:
    - master
matrix:
  include:
  - compiler: gcc
    os: linux
    dist: trusty
  - compiler: clang
    os: osx

script:
- mkdir -p build
- cd build
- cmake -DCMAKE_BUILD_TYPE=Release ..
- cmake --build . --config Release
